NUMPY


In [7]:
import numpy as np
a = [1,2,3,4,5]
print(a)
print(a[1])
print(a[1:4])
print(a[-1])
print(type(a))

[1, 2, 3, 4, 5]
2
[2, 3, 4]
5
<class 'list'>


In [6]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(a[1])
print(a[1:4])
print(a[-1])
print(type(a))

[1 2 3 4 5]
2
[2 3 4]
5
<class 'numpy.ndarray'>


Array Atributy

In [24]:
import numpy as np
a_mul = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a_mul)
print(a_mul.shape)
print(a_mul.ndim)
print(a_mul.size)
print(a_mul.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9
int32


Datové typy

In [37]:
import numpy as np
                #Nesmí být v stringu písmena  #jinak dtype=np.int32 nebude fungovat
# a = np.array([[1,2,3],[4,"Hello",6],[7,8,9]], dtype=np.int32) 
# print(a.dtype)
# print(type(a[0][0]))
# print(a[0][0].dtype)

                #Zde mame cislo ve stringu, dtype funguje
                                        # int32 muzeme nahradit float32
b = np.array([[1,2,3],[4,"5",6],[7,8,9]], dtype=np.int32)
print(b.dtype)
print(type(a[0][0]))
print(b[1][1].dtype)
print(a[1,1])


int32
<class 'numpy.int32'>
int32
5


In [43]:
import numpy as np
d = {'1':'A'}
#Po vložení dictionary se nám z toho stane object
#mužeme tam mít i string
                                            #zde menime datovy typ
b = np.array([[1,2,3],[4,d,6],[7,8,"hello"]], dtype="<U7")
print(b.dtype)
print(type(b[1][0]))

<U7
<class 'numpy.str_'>


Filling arrays

In [48]:
import numpy as np
#2 vytvori dva listy
#3 vytvori tri listy ve dvou listech
#4 vytvori ctyri prvky ve trech listech ktery jsou ve dvou listech
#Nakonci je prvek ktery davame do techto listu
a = np.full((2,3,4), 9)
print(a)

b= np.zeros((10,5,2))
print(b)

c= np.ones((10,5,2))
print(c)

d= np.empty((5,5,5))
print(d)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]


In [55]:
import numpy as np
    #cisla od 0 do 1000 , po peti
x_values = np.arange(0,1005,5)
print(x_values) 
    #cisla od 0 do 1000 , pouze dve
x_values = np.linspace(0,1000,1001)
print(x_values)

[   0    5   10   15   20   25   30   35   40   45   50   55   60   65
   70   75   80   85   90   95  100  105  110  115  120  125  130  135
  140  145  150  155  160  165  170  175  180  185  190  195  200  205
  210  215  220  225  230  235  240  245  250  255  260  265  270  275
  280  285  290  295  300  305  310  315  320  325  330  335  340  345
  350  355  360  365  370  375  380  385  390  395  400  405  410  415
  420  425  430  435  440  445  450  455  460  465  470  475  480  485
  490  495  500  505  510  515  520  525  530  535  540  545  550  555
  560  565  570  575  580  585  590  595  600  605  610  615  620  625
  630  635  640  645  650  655  660  665  670  675  680  685  690  695
  700  705  710  715  720  725  730  735  740  745  750  755  760  765
  770  775  780  785  790  795  800  805  810  815  820  825  830  835
  840  845  850  855  860  865  870  875  880  885  890  895  900  905
  910  915  920  925  930  935  940  945  950  955  960  965  970  975
  980 

In [60]:
import numpy as np
print(np.nan)
print(np.inf)

print(np.isnan(np.nan))
print(np.isnan(np.sqrt(-1)))

print(np.isinf(np.inf))


nan
inf
True
True
True


C:\Users\PC\AppData\Local\Temp\ipykernel_14464\4082825739.py:5: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(-1)))


Matematicke operace

In [66]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,0]

a1 = np .array(l1)
a2 = np .array(l2)

#Python list
print(l1*5)
#np list
print(a1*5)
print(a1+5)

print(l1+l2)
print(a1+a2)
#Jde o to že většina operací nefunguje s python listem
#S np listem funguje vice operaci

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]
[ 6  7  8  9 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[ 7  9 11 13  5]


In [69]:
#Nelze
a1  = np.array([1,2,3])
a2 = np.array([1,1,1],[2,1,1])
print(a1+a2)

TypeError: Field elements must be 2- or 3-tuples, got '2'

In [72]:
#Muzeme pouzit ruzne operace jako sqrt, cos , sin ...
a = np.array([[1,2,3],[4,5,4]])
print(np.sqrt(a))
print(np.cos(a))
print(np.log10(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.        ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219 -0.65364362]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.60205999]]


Array metody

In [81]:
a = np.array([1,2,3])
b =np.append(a,[7,8,9])
#Povšimni si že se to neuloží, měl bys tedy np.append nějak definovat
print(a)
print(b)
#Insertujeme na index 3 ,cisla v seznamu
c =np.insert(a,3,[4,5,6])
print(c)
#Deletne cislo na indexu 1, tedy 2
print(np.delete(a,1))




[1 2 3]
[1 2 3 7 8 9]
[1 2 3 4 5 6]
[1 3]


Strukturovaci metody

In [87]:
#Zde muzeme menit list
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])

print(a.shape)
print(a.reshape((5,4)))
print(a.reshape((20,)))
print(a.reshape((20,1)))
print(a.reshape((2,10)))
print(a.reshape((5,2,2)))

(4, 5)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


In [98]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])
print(a.shape)
print(a.reshape(10,2))
print(a.flatten())
print(a.ravel())

var1 = a.flatten()
var1[2] = 100
print(var1)

var2 = a.ravel()
var2[2] = 100
print(var2)



(4, 5)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]


In [101]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])
print(a)
print(a.T)
print(a.swapaxes(0,1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
